"""add is_key to film_credits

Revision ID: 1cf8eeb0c50d
Revises: cf8b64b1f668
Create Date: 2026-04-15 10:21:16.484398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf8eeb0c50d'
down_revision: Union[str, Sequence[str], None] = 'cf8b64b1f668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_credits', sa.Column('is_key', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film_credits', 'is_key')
    # ### end Alembic commands ###
