"""add backdrop_path to films

Revision ID: 1f2e9ec013c5
Revises: 5644e678bc17
Create Date: 2026-04-07 17:32:24.457635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2e9ec013c5'
down_revision: Union[str, Sequence[str], None] = '5644e678bc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('backdrop_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'backdrop_path')
    # ### end Alembic commands ###
