"""add user_list_likes table and likes_count views_count to user_lists

Revision ID: 4643cce5c096
Revises: 7e4e018a062e
Create Date: 2026-05-20 16:09:58.054710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4643cce5c096'
down_revision: Union[str, Sequence[str], None] = '7e4e018a062e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_list_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'list_id', name='uq_user_list_like')
    )
    op.add_column('user_lists', sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_lists', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lists', 'views_count')
    op.drop_column('user_lists', 'likes_count')
    op.drop_table('user_list_likes')
    # ### end Alembic commands ###
