"""add cover_film_ids to user_list

Revision ID: 7e4e018a062e
Revises: e52d34cfe4a2
Create Date: 2026-05-20 11:05:41.152723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e4e018a062e'
down_revision: Union[str, Sequence[str], None] = 'e52d34cfe4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lists', sa.Column('cover_film_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lists', 'cover_film_ids')
    # ### end Alembic commands ###
