"""drop genres from films

Revision ID: 9fe388ca5b56
Revises: 4ae465ed043d
Create Date: 2026-03-24 18:22:14.316735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe388ca5b56'
down_revision: Union[str, Sequence[str], None] = '4ae465ed043d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
