"""add liked_lists_public to users table

Revision ID: ba922e93d98a
Revises: 094c7dbfa8c9
Create Date: 2026-05-26 22:58:14.919886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba922e93d98a'
down_revision: Union[str, Sequence[str], None] = '094c7dbfa8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('liked_lists_public', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'liked_lists_public')
    # ### end Alembic commands ###
