"""remove is_favorite from user_films

Revision ID: d2eb308e0eed
Revises: 8299e4b267c9
Create Date: 2026-05-07 13:55:31.192557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2eb308e0eed'
down_revision: Union[str, Sequence[str], None] = '8299e4b267c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_films', 'is_favorite')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_films', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
