"""add cover_poster_paths to user_list

Revision ID: e52d34cfe4a2
Revises: eba26061f80e
Create Date: 2026-05-20 10:22:35.377666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e52d34cfe4a2'
down_revision: Union[str, Sequence[str], None] = 'eba26061f80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_lists', sa.Column('cover_poster_paths', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lists', 'cover_poster_paths')
    # ### end Alembic commands ###
