"""update privacy fields

Revision ID: eba26061f80e
Revises: fab7c13c086a
Create Date: 2026-05-19 13:53:40.686146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba26061f80e'
down_revision: Union[str, Sequence[str], None] = 'fab7c13c086a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('want_to_watch_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('watching_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('completed_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('dropped_public', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('lists_public', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_column('users', 'watchlist_public')
    op.drop_column('users', 'stats_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stats_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('watchlist_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'lists_public')
    op.drop_column('users', 'dropped_public')
    op.drop_column('users', 'completed_public')
    op.drop_column('users', 'watching_public')
    op.drop_column('users', 'want_to_watch_public')
    # ### end Alembic commands ###
