"""add profile fields to users

Revision ID: fab7c13c086a
Revises: 9f41c48cb117
Create Date: 2026-05-18 15:07:46.390328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fab7c13c086a'
down_revision: Union[str, Sequence[str], None] = '9f41c48cb117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_path', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pinned_film_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('pinned_list_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('users', sa.Column('watchlist_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('favorites_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('activity_public', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('stats_public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stats_public')
    op.drop_column('users', 'activity_public')
    op.drop_column('users', 'favorites_public')
    op.drop_column('users', 'watchlist_public')
    op.drop_column('users', 'pinned_list_ids')
    op.drop_column('users', 'pinned_film_ids')
    op.drop_column('users', 'avatar_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
